# Shape and Reshape in Numpy Arrays

In [2]:
import numpy as np

In [6]:
p = np.array([1,2,3,4,5,6])
p

array([1, 2, 3, 4, 5, 6])

In [7]:
p.ndim

1

In [8]:
p.shape

(6,)

In [9]:
p.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
p.ndim

1

In [11]:
s = np.array([True,False,True,False])
s

array([ True, False,  True, False])

In [12]:
s.shape

(4,)

In [13]:
s.reshape(2,2)

array([[ True, False],
       [ True, False]])

In [15]:
h = np.array([12.3,34.65,1.4,3.65,98.5,6.43])
h

array([12.3 , 34.65,  1.4 ,  3.65, 98.5 ,  6.43])

In [16]:
h.reshape(3,2)

array([[12.3 , 34.65],
       [ 1.4 ,  3.65],
       [98.5 ,  6.43]])

In [20]:
r = np.array([5+8j,7+8j,23+54j,8+65j])
r

array([ 5. +8.j,  7. +8.j, 23.+54.j,  8.+65.j])

In [21]:
r.reshape(2,2)

array([[ 5. +8.j,  7. +8.j],
       [23.+54.j,  8.+65.j]])

In [22]:
y = np.array([[12,32,54,66,54,87,43,56,9,32,45,22]])
y

array([[12, 32, 54, 66, 54, 87, 43, 56,  9, 32, 45, 22]])

In [23]:
y.ndim

2

In [24]:
y.reshape(3,4)

array([[12, 32, 54, 66],
       [54, 87, 43, 56],
       [ 9, 32, 45, 22]])

In [25]:
y.reshape(2,2,3)

array([[[12, 32, 54],
        [66, 54, 87]],

       [[43, 56,  9],
        [32, 45, 22]]])

Convert 3-D into 1-D

In [26]:
t = np.array([[[23,43,54,65,78,32,45,65,12,65,32,57]]])        # 3-D
t

array([[[23, 43, 54, 65, 78, 32, 45, 65, 12, 65, 32, 57]]])

In [27]:
t.ndim

3

In [28]:
t.reshape(-1)                     # 1-D

array([23, 43, 54, 65, 78, 32, 45, 65, 12, 65, 32, 57])

# Arithmetic Operation in Numpy Arrays

np.min(x)                                                                                                                                  
np.max(x)                                                                                
np.argmin(x)                                                                                          
np.sqrt(x)                                                                                      
np.sin(x)                                                                                    
np.cos(x)                                                                                            
np.cumsum(x)                                                                                  

In [31]:
i = np.array([75,54,98,43,12,54,36,87,54,35,65,45])
i

array([75, 54, 98, 43, 12, 54, 36, 87, 54, 35, 65, 45])

In [33]:
i.reshape(3,4)

array([[75, 54, 98, 43],
       [12, 54, 36, 87],
       [54, 35, 65, 45]])

In [34]:
np.min(i)

12

In [35]:
np.max(i)

98

In [36]:
np.argmin(i)     # find index value

4

In [37]:
np.argmax(i)

2

In [38]:
o = np.array([144,64,81,100])
o

array([144,  64,  81, 100])

In [39]:
np.sqrt(o)

array([12.,  8.,  9., 10.])

In [40]:
np.cos(o)

array([0.8711474 , 0.39185723, 0.77668598, 0.86231887])

In [41]:
np.sin(o)

array([-0.49102159,  0.92002604, -0.62988799, -0.50636564])

In [42]:
e = np.array([1,2,3,4])
e

array([1, 2, 3, 4])

In [43]:
np.cumsum(e)

array([ 1,  3,  6, 10], dtype=int32)

Their are two types of axis:-                                                                                      
    1) axis = 0   (work along column)                                             
    2) axis = 1   (work along row)

In [46]:
u = np.array([[2,7,4],[6,3,8]])
u

array([[2, 7, 4],
       [6, 3, 8]])

In [47]:
np.min(u,axis=0)

array([2, 3, 4])

In [48]:
np.max(u,axis=1)

array([7, 8])

In [61]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [65]:
np.min(x,axis=1)

array([[1, 2, 3]])

In [66]:
np.max(x,axis=1)

array([[7, 8, 9]])

# Broadcasting Numpy Arrays

In [1]:
import numpy as np

In [3]:
y = np.array([1,2,3,4])
x = np.array([4,5,6,7])
y+x

array([ 5,  7,  9, 11])

In [7]:
j = np.array([1,2,4])
k = np.array([1,2,3])
j+k

array([2, 4, 7])

In [8]:
l = np.array([1,2,3,4,np.nan,6,7,np.nan,9,10,np.nan,12,13,14,15,np.nan,17,18,np.nan,20])
l

array([ 1.,  2.,  3.,  4., nan,  6.,  7., nan,  9., 10., nan, 12., 13.,
       14., 15., nan, 17., 18., nan, 20.])

In [9]:
l.reshape(4,5)

array([[ 1.,  2.,  3.,  4., nan],
       [ 6.,  7., nan,  9., 10.],
       [nan, 12., 13., 14., 15.],
       [nan, 17., 18., nan, 20.]])

In [12]:
u = np.array([2])
s = l+u
s

array([ 3.,  4.,  5.,  6., nan,  8.,  9., nan, 11., 12., nan, 14., 15.,
       16., 17., nan, 19., 20., nan, 22.])

In [13]:
s.reshape(4,5)

array([[ 3.,  4.,  5.,  6., nan],
       [ 8.,  9., nan, 11., 12.],
       [nan, 14., 15., 16., 17.],
       [nan, 19., 20., nan, 22.]])

In [14]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [16]:
y = np.array([[1],[2],[3]])
y

array([[1],
       [2],
       [3]])

In [17]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [18]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

# Indexing Numpy Arrays

In [1]:
import numpy as np

In [2]:
j = np.array([22,33,44,55,66,77,88,99])
j

array([22, 33, 44, 55, 66, 77, 88, 99])

In [3]:
j[3]

55

In [4]:
j[-3]

77

In [5]:
k = np.array([[5,6,7],[8,4,9]])
k

array([[5, 6, 7],
       [8, 4, 9]])

In [10]:
k[1]

array([8, 4, 9])

In [11]:
k[0]

array([5, 6, 7])

In [12]:
k[0,1]

6

In [13]:
k[1,2]

9

In [14]:
l = np.array([[[4,3,5],[7,6,5],[9,2,5]]])
l

array([[[4, 3, 5],
        [7, 6, 5],
        [9, 2, 5]]])

In [16]:
l[0,1,1]

6

In [17]:
l[0,2,1]

2

In [18]:
q = np.array([[[[[34,54,65],[76,45,23],[98,77,34]]]]])
q

array([[[[[34, 54, 65],
          [76, 45, 23],
          [98, 77, 34]]]]])

In [19]:
q.ndim

5

In [20]:
q[0,0,0,1,2]

23

# Slicing Numpy Arrays

In [21]:
i = np.array([10,20,30,40,50,60,70,80,90])
i

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
i[2:7]

array([30, 40, 50, 60, 70])

In [26]:
i[-6:-2]

array([40, 50, 60, 70])

In [29]:
D = np.array([[10,20,30],[30,40,50]])
D

array([[10, 20, 30],
       [30, 40, 50]])

In [31]:
D[1,1:3]

array([40, 50])

In [32]:
t = np.array([[[23,34,45],[56,67,78],[89,90,97]]])
t

array([[[23, 34, 45],
        [56, 67, 78],
        [89, 90, 97]]])

In [37]:
t[0,1:3,0:2]

array([[56, 67],
       [89, 90]])

In [38]:
t[0,1:3,1:3]

array([[67, 78],
       [90, 97]])

In [39]:
u = np.array([[[[[1,2,3,4,5],[10,20,30,40,50],[5,6,7,8,9],[15,16,17,18,19],[50,11,60,12,70]]]]])
u

array([[[[[ 1,  2,  3,  4,  5],
          [10, 20, 30, 40, 50],
          [ 5,  6,  7,  8,  9],
          [15, 16, 17, 18, 19],
          [50, 11, 60, 12, 70]]]]])

In [40]:
u[0,0,0,2:5,1:4]

array([[ 6,  7,  8],
       [16, 17, 18],
       [11, 60, 12]])

In [41]:
u[0,0,0,0:3,2:5]

array([[ 3,  4,  5],
       [30, 40, 50],
       [ 7,  8,  9]])

In [42]:
u[0,0,0,3,2]

17

In [44]:
u[0,0,0,4,1:]

array([11, 60, 12, 70])

# Iterating Numpy Arrays

In [45]:
u = np.array([1,2,3,4,5,6,7,8,9])
u

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
for i in u:
    print(i)

1
2
3
4
5
6
7
8
9


In [47]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
for i in x:
    for k in i:
        print(k)

1
2
3
4
5
6
7
8


In [50]:
j = np.array([[[1,2,3,4],[5,6,7,8],[9,6,3,2]]])
j

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 6, 3, 2]]])

In [51]:
for i in j:
    for k in i:
        for s in k:
            print(s)

1
2
3
4
5
6
7
8
9
6
3
2


In [52]:
u = np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
u

array([[[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]]])

In [54]:
for i in u:
    for k in i:
        for s in k:
            for w in s:
                for r in w:
                    print(r)

1
2
3
4
5
6
7
8
9


Second method is:- we can use nditer(variable)

In [55]:
u

array([[[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]]])

In [56]:
for i in np.nditer(u):
    print(i)

1
2
3
4
5
6
7
8
9


In [57]:
h = np.array([[[[10,20,30],[40,50,60],[70,80,90]]]])
h

array([[[[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]]])

In [59]:
for i in np.nditer(h):
    print(i)

10
20
30
40
50
60
70
80
90


In [60]:
h

array([[[[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]]])

In [62]:
for i in np.ndenumerate(h):       # ndenumerate shows index numbers
    print(i)

((0, 0, 0, 0), 10)
((0, 0, 0, 1), 20)
((0, 0, 0, 2), 30)
((0, 0, 1, 0), 40)
((0, 0, 1, 1), 50)
((0, 0, 1, 2), 60)
((0, 0, 2, 0), 70)
((0, 0, 2, 1), 80)
((0, 0, 2, 2), 90)


In [63]:
k = np.array([10,20,30,40,50])
k

array([10, 20, 30, 40, 50])

In [64]:
for i in np.ndenumerate(k):
    print(i)

((0,), 10)
((1,), 20)
((2,), 30)
((3,), 40)
((4,), 50)
