# Resize

In [2]:
import numpy as np

In [3]:
var = np.array([1,2,3,4,5,6,7,8,9])
var

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
var.resize(3,3)

In [5]:
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Flatten And Ravel

In [6]:
u = np.array([[2,4,6],[1,3,5]])
u

array([[2, 4, 6],
       [1, 3, 5]])

In [7]:
u.flatten()

array([2, 4, 6, 1, 3, 5])

In [9]:
i = np.array([[4,5,6],[7,8,9]])
i

array([[4, 5, 6],
       [7, 8, 9]])

In [10]:
i.ravel()

array([4, 5, 6, 7, 8, 9])

In [11]:
y = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
y

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
y.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
y.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
i = np.array([[[[[[[[[[2,3,4],[5,6,7],[8,9,1]]]]]]]]]])
i

array([[[[[[[[[[2, 3, 4],
               [5, 6, 7],
               [8, 9, 1]]]]]]]]]])

In [15]:
i.ndim

10

In [16]:
i.flatten()

array([2, 3, 4, 5, 6, 7, 8, 9, 1])

In [17]:
i.ravel()

array([2, 3, 4, 5, 6, 7, 8, 9, 1])

In [18]:
i

array([[[[[[[[[[2, 3, 4],
               [5, 6, 7],
               [8, 9, 1]]]]]]]]]])

In [20]:
i.flatten(order='a')

array([2, 3, 4, 5, 6, 7, 8, 9, 1])

In [21]:
i.flatten(order='k')

array([2, 3, 4, 5, 6, 7, 8, 9, 1])

In [23]:
i.flatten(order='c')

array([2, 3, 4, 5, 6, 7, 8, 9, 1])

In [24]:
i.flatten(order='f')

array([2, 5, 8, 3, 6, 9, 4, 7, 1])

# Insert

In [25]:
u = np.array([1,2,3,4,5,7,8,9])
u

array([1, 2, 3, 4, 5, 7, 8, 9])

In [30]:
s = np.insert(u,5,6)
s

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
y = np.array(["a","b","d","e","f"])
t = np.insert(y,2,"c")
t

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [35]:
u

array([1, 2, 3, 4, 5, 7, 8, 9])

In [39]:
k = np.insert(u,(5,8),6)                                 
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6])

In [40]:
h = np.insert(u,5,6.4)
h

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
j = np.array([[11,12,13],[14,np.nan,16]])
j

array([[11., 12., 13.],
       [14., nan, 16.]])

In [57]:
s = np.insert(j,1,1,15)
s

AxisError: axis 15 is out of bounds for array of dimension 2

In [58]:
k = np.insert(j,2,6)
k

array([11., 12.,  6., 13., 14., nan, 16.])

In [59]:
k = np.insert(j,2,6,axis=0)
k

array([[11., 12., 13.],
       [14., nan, 16.],
       [ 6.,  6.,  6.]])

In [60]:
k = np.insert(j,2,6,axis=1)
k

array([[11., 12.,  6., 13.],
       [14., nan,  6., 16.]])

In [61]:
u = np.insert(j,2,[17,18,19])
u

array([11., 12., 17., 18., 19., 13., 14., nan, 16.])

In [63]:
u = np.insert(j,2,[17,18,19],axis=0)
u

array([[11., 12., 13.],
       [14., nan, 16.],
       [17., 18., 19.]])

# Append

In [64]:
j = np.array([1,2,3,4,5,6,7])
j

array([1, 2, 3, 4, 5, 6, 7])

In [66]:
s = np.append(j,8)
s

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
u = np.array([[1,2,3],[4,5,6]])
u

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
t = np.append(u,7)
t

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
e = np.append(u,[7,8,9])
e

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
u

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
e = np.append(u,[[7,8,9]],axis=0)
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Delete

In [75]:
var = np.array([1,2,3,4,5,6,7,8,9,10])
var

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
t = np.delete(var,9)      #  here, 9 is a index value
t

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
u = np.delete(var,4)
u

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10])

# Matrix

Difference between matrix and arrays

here, the difference is multiplication of two matrix and multiplication of two arrays output is different this is a main difference of matrix and arrays

In [99]:
s = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
type(s)

numpy.matrix

In [100]:
u = np.matrix([[1,3,7],[2,4,6],[3,6,9]])
type(u)

numpy.matrix

In [101]:
s*u   # matrix does not multiply like this here we can use for multiplication is dot

matrix([[ 14,  29,  46],
        [ 32,  68, 112],
        [ 50, 107, 178]])

In [102]:
s = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
u = np.matrix([[1,3,5],[2,4,6],[3,6,9]])
print(s.dot(u))

[[ 14  29  44]
 [ 32  68 104]
 [ 50 107 164]]


In [104]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[1,3,5],[2,4,6],[3,6,9]])
x*y

array([[ 1,  6, 15],
       [ 8, 20, 36],
       [21, 48, 81]])

In [105]:
print(x.dot(y))            # if we use .dot to multiply two arrays then they multiply same like matrix

[[ 14  29  44]
 [ 32  68 104]
 [ 50 107 164]]


In [106]:
s+u

matrix([[ 2,  5,  8],
        [ 6,  9, 12],
        [10, 14, 18]])

In [107]:
x+y

array([[ 2,  5,  8],
       [ 6,  9, 12],
       [10, 14, 18]])

In [108]:
s-u

matrix([[ 0, -1, -2],
        [ 2,  1,  0],
        [ 4,  2,  0]])

In [109]:
x-y

array([[ 0, -1, -2],
       [ 2,  1,  0],
       [ 4,  2,  0]])

# Matrix Function

In [110]:
var = np.matrix([[1,2,3],[4,5,6]])
var

matrix([[1, 2, 3],
        [4, 5, 6]])

In [111]:
np.transpose(var)

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [114]:
j = np.array([[10,20,30],[40,50,60]])
j

array([[10, 20, 30],
       [40, 50, 60]])

In [115]:
np.transpose(j)

array([[10, 40],
       [20, 50],
       [30, 60]])

In [121]:
h = np.matrix([[11,12,13],[14,15,16],[17,18,19]])
h

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [123]:
print(h.T)

[[11 14 17]
 [12 15 18]
 [13 16 19]]


In [128]:
y = np.matrix([[1,2,3],[4,5,6]])
print(y)
print()
print(np.swapaxes(y,1,1))

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [129]:
y = np.matrix([[1,2,3],[4,5,6]])
print(y)
print()
print(np.swapaxes(y,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


# Inverse Matrix

In [135]:
num = np.matrix([[10,20],[40,50]])
num

matrix([[10, 20],
        [40, 50]])

In [137]:
np.linalg.inv(num)

matrix([[-0.16666667,  0.06666667],
        [ 0.13333333, -0.03333333]])

In [138]:
num

matrix([[10, 20],
        [40, 50]])

In [139]:
np.linalg.matrix_power(num,2)

matrix([[ 900, 1200],
        [2400, 3300]])

In [140]:
np.linalg.matrix_power(num,1)

matrix([[10, 20],
        [40, 50]])

Determinate

In [146]:
k = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
k

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [147]:
np.linalg.det(k)

6.66133814775094e-16

In [149]:
var = np.matrix([[1,2],[3,4]])
var

matrix([[1, 2],
        [3, 4]])

In [150]:
print(np.linalg.det(var5))

-2.0000000000000004


Numpy is Over