# Creating Numpy Arrays

# Array

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [3]:
y = np.array([[1,2],[3,4]])
y

array([[1, 2],
       [3, 4]])

In [4]:
x.ndim

1

In [5]:
y.ndim

2

In [13]:
t = np.array([[[1,2,3],[4,5,6]]])
t

array([[[1, 2, 3],
        [4, 5, 6]]])

In [14]:
t.ndim

3

In [15]:
t.dtype

dtype('int32')

In [16]:
t = np.array([[[1,2,3],[4,5,6]]],dtype='int8')
t

array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int8)

In [17]:
t.dtype

dtype('int8')

In [18]:
h = np.array([[1,2],[3,4]],ndmin=10)
h

array([[[[[[[[[[1, 2],
               [3, 4]]]]]]]]]])

In [19]:
h.ndim

10

# Zeros

In [12]:
r = np.zeros(3)
r

array([0., 0., 0.])

In [13]:
t = np.zeros([2,3])
t

array([[0., 0., 0.],
       [0., 0., 0.]])

# Ones

In [14]:
g = np.ones(3)
g

array([1., 1., 1.])

In [15]:
x = np.ones([2,3])
x

array([[1., 1., 1.],
       [1., 1., 1.]])

# Empty

In [16]:
r = np.empty(3)
r

array([1., 1., 1.])

In [19]:
g = np.empty([2,3])
g

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
f = np.empty([0])
f

array([], dtype=float64)

# Range

In [20]:
w = np.arange(5)
w

array([0, 1, 2, 3, 4])

In [21]:
j = np.arange(4,9)
j

array([4, 5, 6, 7, 8])

In [22]:
b = np.arange(2,21,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# Diagnol

In [25]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
u = np.eye(2,3)
u

array([[1., 0., 0.],
       [0., 1., 0.]])

In [27]:
n = np.identity(4)
n

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
l = np.identity(2,3)
l

TypeError: Cannot interpret '3' as a data type

In [37]:
p = np.linspace(1,5)
p

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [33]:
q = np.linspace(2,10,num=3)
q

array([ 2.,  6., 10.])

In [35]:
w = np.linspace(5,20,num=4)
w

array([ 5., 10., 15., 20.])

# Create Numpy array with Random Numbers

# Random

random number always lies between 0 to 1.

# Rand

In [32]:
y = np.random.rand(4)
y

array([0.52769057, 0.67944553, 0.25627334, 0.66861538])

In [33]:
k = np.random.rand(3,4)
k

array([[0.57907824, 0.53680094, 0.3969994 , 0.48363758],
       [0.50360244, 0.87937804, 0.79509637, 0.09340203],
       [0.53814038, 0.54928237, 0.47440452, 0.11921294]])

In [34]:
u = np.random.rand(2,4,2)
u

array([[[0.3364179 , 0.82912118],
        [0.52132507, 0.35284592],
        [0.97883862, 0.04468027],
        [0.53893575, 0.87548182]],

       [[0.40348308, 0.29610734],
        [0.13134571, 0.65276388],
        [0.36693429, 0.23220861],
        [0.90796368, 0.69174699]]])

# Randn

Randn always lies between 0 to 1 but here both positive and negative values will come.

In [36]:
h = np.random.randn(2,3)
h

array([[-0.33095673, -0.69263916, -1.32795672],
       [-0.56505743,  1.00122692, -1.803346  ]])

In [37]:
h.ndim

2

In [38]:
u = np.random.randn(2,2,4)
u

array([[[ 1.40674421,  1.85908253, -0.94267205, -0.91059078],
        [ 1.17387877,  0.07807398, -0.58833285,  0.77612788]],

       [[ 1.50949311,  0.76368143, -1.67958838, -0.13800146],
        [ 1.06442507,  0.2100328 ,  1.76491656,  0.62484081]]])

In [39]:
u.ndim

3

# Ranf

Ranf will give value in the zeros

In [40]:
p = np.random.ranf(4)
p

array([0.91911611, 0.51113731, 0.89026878, 0.6711778 ])

In [42]:
o = np.random.ranf([3,4])
o

array([[0.5824684 , 0.19157293, 0.85750033, 0.77226472],
       [0.39968884, 0.99350251, 0.81665632, 0.88840695],
       [0.38729859, 0.86326632, 0.88049203, 0.22294697]])

In [43]:
u = np.random.ranf([3,3])
u

array([[0.80672929, 0.29284355, 0.74024933],
       [0.9266721 , 0.28896176, 0.26107653],
       [0.27203574, 0.3162399 , 0.60862332]])

# Randint

Here, we will decide two number and between two number is called randint

In [44]:
j = np.random.randint([3,9])
j

array([2, 6])

In [47]:
l = np.random.randint([1,20])
l

array([0, 4])

In [56]:
u = np.random.randint([2,10,2])
u

array([0, 5, 1])

In [60]:
l = np.random.randint([1,20,5])
l

array([0, 2, 3, 0])

# Data Types in Numpy Arrays

bool = true false                                                                                              
int = int64, int32                                                                                              
int8 = Byte(-128 to 127)                                                                                          
int16 = integer (-32768 to 32767)                                                                                            
int32 = integer (-2147483648 to 2147483647)                                                                                   
int64 = integer (-9223372036854 to 9223372036854)                                                                       
float16 = 5 bits to 10 bits                                                                                              
float32 = 8 bits to                                                                                                  
float64 = 11 bit to                                                                                           

Data Type

In [62]:
k = np.array([1,2,3,4])
k.dtype

dtype('int32')

In [64]:
y = np.array([1.2,3.3,5.4,8.7])
y.dtype

dtype('float64')

In [65]:
c = np.array(["a","b","c","d"])
c.dtype

dtype('<U1')

In [66]:
u = np.array(["a","b","c",3,8,2])
u.dtype

dtype('<U11')

In [67]:
b = np.array(["a","b","c",4.3,2.3,6.5])
b.dtype

dtype('<U32')

In [71]:
i = np.array(["a","b","c","d",7.4,8,9,32,54,76.43,5.34,98,45,True])
i.dtype

dtype('<U32')

In [70]:
l = np.array([True,False,False,False,True,True,False])
l.dtype

dtype('bool')

In [72]:
h = np.array([7+2j,9+3j])
h

array([7.+2.j, 9.+3.j])

In [73]:
h.dtype

dtype('complex128')

In [74]:
x = np.array([2,3,4,5])
x.dtype

dtype('int32')

In [76]:
y = np.array([2,3,4,5],dtype='int16')
y.dtype

dtype('int16')

In [82]:
z = np.array([2,3,4,5],dtype='f')
z.dtype

dtype('float32')

In [83]:
t = np.array([2,3,4,5],dtype='float16')
t.dtype

dtype('float16')