# Difference Between copy and view

In [2]:
import numpy as np

In [3]:
h = np.array([2,4,6,8])
h

array([2, 4, 6, 8])

In [4]:
j = h.copy()
j

array([2, 4, 6, 8])

In [6]:
h[2]=5

In [7]:
h

array([2, 4, 5, 8])

In [8]:
j

array([2, 4, 6, 8])

In [17]:
s = np.array([1,3,5,7])
s

array([1, 3, 5, 7])

In [18]:
k = s.view()
k

array([1, 3, 5, 7])

In [19]:
s[2]=4

In [20]:
s

array([1, 3, 4, 7])

In [21]:
k

array([1, 3, 4, 7])

In [22]:
y = np.array([1,2,3,4,5,6,7,8,9])
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
e = y.copy()
e

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
u = y.view()
u

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
y[4]=0

In [26]:
y

array([1, 2, 3, 4, 0, 6, 7, 8, 9])

In [27]:
e

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
u

array([1, 2, 3, 4, 0, 6, 7, 8, 9])

In [37]:
var = np.array([[1,2,3],[4,5,6]])
var

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
var1 = var.copy()
var1

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
var2 = var.view()
var2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
var[1]=7

In [43]:
var

array([[1, 2, 3],
       [7, 7, 7]])

In [45]:
var1

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
var2

array([[1, 2, 3],
       [7, 7, 7]])

In [51]:
var[1][1]=8
var[1][2]=9

In [52]:
var

array([[1, 2, 3],
       [7, 8, 9]])

In [53]:
var1

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
var2

array([[1, 2, 3],
       [7, 8, 9]])


# Join Array

In [29]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
s = np.concatenate([var1,var2])
s

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
g = np.array([1,2,3])
j = np.array([4,5,6])
e = np.concatenate((g,j))
e

array([1, 2, 3, 4, 5, 6])

In [33]:
u = np.array([[1,2,3],[4,5,6]])
i = np.array([[10,20,30],[40,50,60]])
h = np.concatenate([u,i])
h

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [64]:
u = np.array([[1,2,3],[4,5,6]])                               # axis = 1
i = np.array([[10,20,30],[40,50,60]])
h = np.concatenate([u,i],axis=1)
h

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [59]:
h = np.array([2,4,6,8])
o = np.array([1,3,5,7])
t = np.stack((h,o))
t

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [62]:
h = np.array([2,4,6,8])                              # axis = 1
o = np.array([1,3,5,7])
t = np.stack((h,o),axis=1)
t

array([[2, 1],
       [4, 3],
       [6, 5],
       [8, 7]])

In [65]:
h = np.array([2,4,6,8])
o = np.array([1,3,5,7])
t = np.hstack((h,o))
t

array([2, 4, 6, 8, 1, 3, 5, 7])

In [66]:
h = np.array([2,4,6,8])
o = np.array([1,3,5,7])
t = np.vstack((h,o))
t

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [67]:
h = np.array([2,4,6,8])
o = np.array([1,3,5,7])
t = np.dstack((h,o))
t

array([[[2, 1],
        [4, 3],
        [6, 5],
        [8, 7]]])

In [68]:
r = np.array([[1,2,3],[4,5,6]])
e = np.array([[2,4,6],[1,3,5]])
g = np.stack([r,e])
g

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 4, 6],
        [1, 3, 5]]])

In [69]:
r = np.array([[1,2,3],[4,5,6]])
e = np.array([[2,4,6],[1,3,5]])
g = np.hstack([r,e])
g

array([[1, 2, 3, 2, 4, 6],
       [4, 5, 6, 1, 3, 5]])

In [70]:
r = np.array([[1,2,3],[4,5,6]])
e = np.array([[2,4,6],[1,3,5]])
g = np.vstack([r,e])
g

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6],
       [1, 3, 5]])

In [71]:
r = np.array([[1,2,3],[4,5,6]])
e = np.array([[2,4,6],[1,3,5]])
g = np.dstack([r,e])
g

array([[[1, 2],
        [2, 4],
        [3, 6]],

       [[4, 1],
        [5, 3],
        [6, 5]]])

# Split Array

In [91]:
u = np.array([1,2,3,4,5,6])
i = np.array_split(u,2)
i

[array([1, 2, 3]), array([4, 5, 6])]

In [92]:
l = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [93]:
s = np.array_split(l,4)
s

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

In [95]:
o = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
o

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [109]:
u = np.array_split(o,2)
u

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [110]:
u = np.array_split(o,2,axis=1)
u

[array([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13],
        [16, 17, 18]]),
 array([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20]])]

In [111]:
u[0]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [112]:
o

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [113]:
e = np.where(o==8)         # this is show where 8 is present  it means their index number
e

(array([1], dtype=int64), array([2], dtype=int64))

In [117]:
u = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
u

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [118]:
j = np.where((u%2==0))
j

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int64),)

In [119]:
r = np.array([1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19])
r

array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 13, 14, 16, 17, 18, 19])

In [120]:
i = np.searchsorted(r,5)
i

4

In [121]:
w = np.searchsorted(r,10)
w

8

In [122]:
v = np.searchsorted(r,15)
v

12

In [124]:
l = np.searchsorted(r,20)
l

16

In [125]:
p = np.searchsorted(r,50)
p

16

In [126]:
h = np.array([1,44,24,12,64,23,7,53,76,23])
h

array([ 1, 44, 24, 12, 64, 23,  7, 53, 76, 23])

In [139]:
o = np.searchsorted(h,25)
o

7

In [138]:
print(np.sort(h))

[ 1  7 12 23 23 24 44 53 64 76]


In [2]:
var1 = np.array([10,20,30,50,60,70,80])   # this work right to left5
x1 = np.searchsorted(var1,40,side='right')
print(x1)

3


In [4]:
var1 = np.array([10,20,30,50,60,70,80])   # this work left to right
x1 = np.searchsorted(var1,40,side='left')
print(x1)

3


# Filter Array

In [5]:
h = np.array(["a", "b", "c", "s", "d", "e", "o", "l", "f"])
h

array(['a', 'b', 'c', 's', 'd', 'e', 'o', 'l', 'f'], dtype='<U1')

In [6]:
u = [True,True,True,False,True,True,False,False,True]
new = h[u]
print(new)

['a' 'b' 'c' 'd' 'e' 'f']


In [8]:
num = np.array([1,2,8,9,3,4,8,5,1,6,2,7,3,2,8,1,4,9])
correction = [True,True,False,False,True,True,False,True,False,True,False,True,False,False,True,False,False,True]
correct = num[correction]
correct

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
h = np.array([1,2,3,4,"fd",5,6,7,8])
h

array(['1', '2', '3', '4', 'fd', '5', '6', '7', '8'], dtype='<U11')

In [10]:
o = [True,True,True,True,False,True,True,True,True]
u = h[o]
u

array(['1', '2', '3', '4', '5', '6', '7', '8'], dtype='<U11')

# Shuffle

In [36]:
y = np.array(["a","b","c","d","e","f","g","h"])
np.random.shuffle(y)
y

array(['b', 'd', 'h', 'c', 'a', 'e', 'g', 'f'], dtype='<U1')

In [37]:
i = np.array([1,2,3,4,5,6,7,8,9])
np.random.shuffle(i)
i

array([7, 8, 1, 9, 4, 5, 2, 6, 3])

In [39]:
o = np.array([7,3,8,2,6,2,6,9,7,2,4,6,8,1,4,8,5,0])
s = np.unique(o)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
o = np.array([7,3,8,2,6,2,6,9,7,2,4,6,8,1,4,8,5,0])
s = np.unique(o,return_index=True)
s

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([17, 13,  3,  1, 10, 16,  4,  0,  2,  7], dtype=int64))

In [41]:
o = np.array([7,3,8,2,6,2,6,9,7,2,4,6,8,1,4,8,5,0])
s = np.unique(o,return_counts=True)
s

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 1, 3, 1, 2, 1, 3, 2, 3, 1], dtype=int64))